# Generated by Django 4.1 on 2024-03-03 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0003_remove_userprofile_username_userprofile_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user_id",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userdetails",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
